---
vhost_listen_ip: 0.0.0.0
website_name: www.humana.com
website_alias: humana.com
responsible_party: user1@humana.com
http_document_root: /var/www/html
http_error_logs_name: errors.www.humana.com.log
http_access_logs_name: access.www.humana.com.log
ssl_cert_name: example.com.crt
ssl_key_name: example.com.key
ssl_chain_name: ca-certificates.crt
ssl_protocols: all -SSLv3 -TLSv1 -TLSv1.1
ssl_allowed_ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256