---
- hosts: localhost
  gather_facts: True
  become: True
  roles:
    - role: common
      vars:
        fqdn_hostname: ns1.anet.local
        selinux_state: enforcing
    - role: BIND
      vars:
        fqdn_hostname: ns1.anet.local
        dns_sec: no