---
- hosts: localhost
  gather_facts: True
  become: True
  roles:
    - role: common
      vars:
        host_name: nfs
        fqdn_hostname: nfs.anet.internal
        selinux_state: disabled
        root_pw: Passw@ord123!

    - role: NFS
      vars:
        nfs_dir: /mnt/nfs
        nfs_network_access: 0.0.0.0/24