consul_version: "1.8.3"
gossip_encryption_key: b8QnDrMHJEwtayuEcd9M0PS3eHan46OFp++/YWO3S4I=
datacenter_name: dc1
leader_join_address: 192.168.4.3
leader_ssh_user: root
leader_ssh_password: Passw@ord123!